sudo: required

env:
  - IMAGE_NAME="nmuxj"

services:
- docker

before_install:
- cd jenkins
- make denkins

script:
- cd ..
- make build

after_success:
- make travis
- make test-hook || travis_terminate 1
