os: linux
arch: arm64-graviton2

services:
  - docker

env:
  global:
    - secure: lx89M76RhiMdsEZCzZrOgTh2Y5DTdyTTsxSnxnYMLxqf6iqB1kpgbZzbnHMIPF0oM5hjTWn+/+FdePbcmq/ZSXoYJyuDR67VOd762PTG9vochocgROyydWLZz3Mce/YG/8jy91azRm1MpXGqwSx8nFRtrC3hkUf6bu5sIIqUj6mv2911DOFS7N3RjNL7L+SCQR5A1tEMT/bbAlkJbH4qRBy1QO1xK7rYT0qFoCuf/Fpet31CubUgAB2YAdP6rAIBT4xpSw1S2m2WhY92oGvKvKkF2Lu00J25cpvEuuWRo8nOR8sRNZSVJGccna7e939qiA2vumkFL+sDt+UJk7MUB3V4uG6Qttgpv8O+ITz/gUIeO+44q+U8WHvaBkO0co3jB1zjALKMYLW2TsthCBnz8nrN7KGk2JWtNK8XJ5dfPaA5OvNVr2qAab8Pl2bBDrb2qGfOtxlyhmE807ZOm6Io/fz96f/xmaeVRwsFzReeuo6IJzaLzRWGhqNoTpRLek0NFmbPL/DKru4bPLN0z/OwPE11d5CYvOst9XVK8DtDE09k9YhOhbZpiDcbISrzr5fJoaIDqW2dZTwRoRvOHAOLCkfx8PppNnIbgK0s3PVuvbgSFN49jlgu+aBVSz8QXsuweoyxhlZWiwcsxHIHPwlGrTSBcbr+HsGe9hYJK19sCU4=
    - secure: rwr1WBqHs6PGlFPrAJ+IlQJTxn7DAyRYlccLkGSWG1/O0TfpGi7fuqRwnVT1u3g6Jjw1K3q25xBgX1Pv6UbwUqhPGP0H/+IKKY5zg7xYXU32H9Scvt/pjHSv2RNp3RpNVu4NF0CW5IL9WgaABTPv8f8UUjQAdSmgRqNscC0xBQKoI637EdTCnw0dsrZ56M3vudWewyhtNH40yakG6FUYlo4VFENoPHe0ai7YGgJHbelua7NrdZjKqo4zcrQq+WQU35mJWwfkliCh63ux9GQVe0xjgQJktbVmRiuBhhIj1yIPHg9+iiLuf59NqZarG5R/yqtqSDdKtaa3KatVKQf0//IZ9jKDaQ+WByNXRIdlQMdksITGvhbLBh5pikTc5XtAzS+KBchyQHtXuqgPnvGcfP9K6krtBeSPoMuUGAeGyZTxJ28rJsUjxCgOq/dcHC0rruPiz77fTOg2jcikvwYdTm/NiD8ETF2S+NnQq7Ek3ZGwzrZjBp1Njml3QcLnt1AgDtZ0YUATI0BfmgRRauQ0PzsrJV1zFln3dvHLwgDMqnAjd71d62zHAiXjNjsuA+JUVyZcgrzWB4iUH5YN1GO//37TmDYU8OnDGtyqOuedeKtwskNjmnoq/iznAZBZYV2xuJYY3F8Ka4NutwAsnS1WZ09E7q1LNeFlbfnM17J2ggY=

before_install:
  - cd jenkins
  - make jocker

script:
  - cd ..
  - make build

after_success:
  - "./scripts/jenkins-wait.sh jenkins/job/Setup"
  - make travis
  - make test-hook || travis_terminate 1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make release; fi
